### PR TITLE
use R*-Tree for Pareto frontier

### PR DESCRIPTION
**Pull request by alyst**
I've started [SpatialIndexing.jl](https://github.com/alyst/SpatialIndexing.jl) package (implements [R*-tree](https://en.wikipedia.org/wiki/R*_tree)), and this PR uses R*-tree as the container for the Pareto frontier in `EpsBoxArchive` as discussed in #82. Unfortunately, at the moment I'm hitting some internal Julia error JuliaLang/julia#30122. So either that would be fixed or I'll find some workaround to proceed further.

### CODE REVIEW

**Comment by robertfeldt** [comment]
Very nice. Please tell me when you feel it is stable enough to eval and merge.

**Comment by alyst** [comment]
I was running it for a while with 24x parallel evaluator. It looks stable. It also reduces Pareto front update bottleneck, although that requires more benchmarking. JuliaLang/julia#30122 type intersection bug was fixed in 1.0.3/1.1.0/master, so for merging this PR we have to wait until any of these versions are released.

**Comment by robertfeldt** [comment]
Ok, great, let's wait for at least 1.0.3 then. Did you need to do anything in particular for running he parallel evaluator or is this now well enough supported on master? Would be great if you can add some relevant examples/code for this just to help people get started.

**Comment by alyst** [comment]
Julia 1.0.3 is released, so this PR should be fine for evaluation

> Did you need to do anything in particular for running he parallel evaluator or is this now well enough supported on master?

I was testing with async parallel evaluator from #46 (should be better for Borg). It works for me, but I'm hesitating a bit about about merging and promoting it, because it uses a strange/ugly mix of locks/semaphores and `SharedArrays` for synchronization (the result of trying to minimize the overhead of serialization during processes communication).

**Pull request merged**
