### PR TITLE
Julia07fixes

### PR DESCRIPTION
**Pull request by jmgnve**
Automatic changes by femtocleaner

### CODE REVIEW

**Comment by alyst** [comment]
@jmgnve Thanks for this work!
ATM I'm trying to fix the remaining errors/warnings on Julia master using this PR branch as a base. How should we proceed then? I can submit my own PR (my PR will contain all your commits and preserve your authorship). Or you can allow me pushing to your fork of BlackBoxOptim.jl repository, and then I'll add my commits to this PR.

**Comment by jmgnve** [comment]
What is the easiest solution for you? I don't mind if my authorship "vanishes" in the process. I mostly wish for a working package. I can give you admin rights to my fork if that is the best solution for you.

**Comment by alyst** [comment]
I think it would be the easiest for both of us if I'll open the new PR. Then you don't need to configure anything on your side.
I'll do it as soon I make the BBO package to pass the unit tests on my computer. I will also refer to this PR from the new one, so you will automatically get the notification.

**Comment by jmgnve** [comment]
Nice. Tell me if there is anything else I can help with.

**Pull request closed without merging**
