### PR TITLE
Julia v0.4 compatibility

### PR DESCRIPTION
**Pull request by alyst**
There are `Tuple` and `Dict` changes in Julia v0.4 that are not compatible with `BlackBoxOptim`.
The PR updates `Tuple` and `Dict` syntax and also fixes a few other API deprecations.
It uses `Compat` package for backward-compatibility, so it should be compatible with v0.3.x, but I have not tested it.
It also makes a few tiny enhancements and simplifications that I observed during the code migration (int conversions, the usage of abstract types in types and function declarations, replacing Strings by Symbols as dictionary keys).

### CODE REVIEW

**Comment by robertfeldt** [comment]
Thanks for your hard work. This looks useful. However, when I try these patches on v0.3.8 there are problems so I'm reluctant to merge at this point. Comments?

```
feldt:~/tmp/BlackBoxOptim.jl$ rake
julia --color=yes -L src/BlackBoxOptim.jl test/runtests.jl
ERROR: `convert` has no method matching convert(::Type{Union(Type{Optimizer},Function)}, ::Type{SimultaneousPerturbationSA2})
 in setindex! at dict.jl:551
 in Dict at dict.jl:326
 in include at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in process_options at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/feldt/tmp/BlackBoxOptim.jl/src/bboptimize.jl, in expression starting on line 1
while loading /Users/feldt/tmp/BlackBoxOptim.jl/src/BlackBoxOptim.jl, in expression starting on line 132

rake aborted!
Command failed with status (1): [julia --color=yes -L src/BlackBoxOptim.jl ...]
/Users/feldt/tmp/BlackBoxOptim.jl/Rakefile:27:in `block in <top (required)>'
/Users/feldt/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/feldt/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => runtest
(See full trace by running task with --trace)
```

**Comment by alyst** [comment]
Thank you. It looks like there were some changes in type inference in 0.4, so that `SimultaneousPerturbationSA2` is recognized as compatible to that union, but not in 0.3.x. I'm currently investigating how to change this declaration into something that is both informative and valid in 0.3.x.

**Comment by alyst** [comment]
Ok, I've fixed the issues with 0.3.x (most of them looks like bugs in the syntax/type analyser). The tests are passing now.

**Comment by robertfeldt** [comment]
Thanks. Looks close now but I still get one problem when running tests:

```
Search space
     - isinspace
     - Symmetric search space with default range
  Error   :: (line:366) :: Symmetric search space with default range
    ranges(ss3) => ParamBounds[(0.0,1.0),(0.0,1.0),(0.0,1.0)]
`getindex` has no method matching getindex(::Type{(Float64,Float64)}, ::(Float64,Float64), ::(Float64,Float64), ::(Float64,Float64))
 in anonymous at /Users/feldt/.julia/v0.3/FactCheck/src/FactCheck.jl:139
 in anonymous at /Users/feldt/.julia/v0.3/FactCheck/src/FactCheck.jl:142
 in do_fact at /Users/feldt/.julia/v0.3/FactCheck/src/FactCheck.jl:201
 in anonymous at /Users/feldt/tmp/BlackBoxOptim.jl/test/test_search_space.jl:142
 in context at /Users/feldt/.julia/v0.3/FactCheck/src/FactCheck.jl:341
 in anonymous at /Users/feldt/tmp/BlackBoxOptim.jl/test/test_search_space.jl:13
 in facts at /Users/feldt/.julia/v0.3/FactCheck/src/FactCheck.jl:315
 in include at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in anonymous at no file:29
 in include at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
 in _start at /Applications/Julia-0.3.8.app/Contents/Resources/julia/lib/julia/sys.dylib
     - SymmetricSearchSpace with given range
     - rand_individual is within the search space
     - rand_individuals creates many individuals and all are within the search space
     - RangePerDimSearchSpace
     - rand_individuals_lhs samples in LHS intervals
     - feasible finds feasible points in the search space
     - diameters
Out of 2197 total facts:
  Verified: 2196
  Errored:  1
```

**Comment by alyst** [comment]
Hmm, I was replacing my branch several times to get things straight and at some point the code in question (`ranges(ss3) => ParamBounds[(0.0,...`) was fixed. With the current one CI tests seem to pass. Could you please check if after deleting your local `v04_compat` branch checking it out again the error will go away? Sorry for the inconvenience.

**Comment by robertfeldt** [comment]
Yes, that was it. All good.

**Pull request merged**
