### PR TITLE
Fix improper typing

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
There are hardcoded Int64's which will break usage on 32-bit OS's. This fixes the issue by using Int (and so 64-bit is completely unchanged).

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
This fixes at least the reported errors from https://github.com/robertfeldt/BlackBoxOptim.jl/issues/63

**Comment by robertfeldt** [comment]
Ok, this sounds good. I want to clean up the latest tagged version anyway and get some new stuff in there. Will check this and get back to you.

**Comment by robertfeldt** [comment]
This is against master, right?

**Comment by ChrisRackauckas** [comment]
Yes.

**Comment by robertfeldt** [comment]
Ok, it looks good but one test fails on 64-bit machine since shot() on DictChain will print Int64 and not Int. Any good suggestions for this? Different tests depending on the machine?

**Comment by ChrisRackauckas** [comment]
Just interpolate in the Int type. That fixed the test.

**Comment by robertfeldt** [comment]
Ah, nicer solution than mine, thanks.

**Pull request merged**
