### PR TITLE
update to julia v0.7

### PR DESCRIPTION
**Pull request by alyst**
This is the continuation of PR #89.

Closes #89

### CODE REVIEW

**Comment by alyst** [comment]
Passes unit tests on my machine with 1 day old master.

There's one warning for which I cannot locate the source
```
┌ Warning: `a::AbstractArray + b::Number` is deprecated, use `a .+ b` instead.
│   caller = top-level scope at Test.jl:1082
└ @ Core ~/aur/julia-git/src/julia/usr/share/julia/stdlib/v0.7/Test/src/Test.jl:1082
```

**Comment by jpsamaroo** [comment]
@alyst Line 32 in `test_mutation_operators.jl`, the `+=` should be `.+=`. Changing that (as well as adding a `global` keyword before `numtestfiles` in `runtests.jl`) removes all depwarns for me, and all tests pass. I recommend running Julia with `--depwarn=error` next time you're trying to track one of these down (that showed me the name of the testset in which the error occurred, which was enough to pinpoint it).

**Comment by alyst** [comment]
@jpsamaroo Thanks! The only problem of `--depwarn=error` is that it interrupts the tests. I wonder if there's a way to make logging report stacktraces for warnings without interrupting the flow (e.g. with some customized logger).

**Comment by alyst** [comment]
It turns out, `numtestfiles` warning was actually JuliaLang/julia#28269

**Comment by robertfeldt** [comment]
This looks good. Currently I have'nt tried it in depth since my julia 0.7 built from sources has problems precompiling Arpack, PDMats and Distributions and we rely on the latter. Will fix/check soon. Are we ready to merge or do you foresee more changes to this PR in short-term?

**Comment by robertfeldt** [comment]
Hmm, installed 0.7.0-beta2 from the dmg files on julialang.org but there are LoadErrors's:

```
feldt:~/tmp/BlackBoxOptim.jl$ rake runtest7
julia07 --depwarn=no --color=yes -L src/BlackBoxOptim.jl test/runtests.jl
ERROR: LoadError: LoadError: syntax: too few type parameters specified in "new{...}"
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1034
 [3] include at ./sysimg.jl:29 [inlined]
 [4] include(::String) at /Users/feldt/.julia/packages/BlackBoxOptim/mCix/src/BlackBoxOptim.jl:3
 [5] top-level scope at none:0
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1034
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:0
 [10] eval at ./boot.jl:319 [inlined]
 [11] eval(::Expr) at ./client.jl:394
 [12] top-level scope at ./none:3 [inlined]
 [13] top-level scope at ./<missing>:0
in expression starting at /Users/feldt/.julia/packages/BlackBoxOptim/mCix/src/parameters.jl:1
in expression starting at /Users/feldt/.julia/packages/BlackBoxOptim/mCix/src/BlackBoxOptim.jl:93
```

Does this need to run on the latest 0.7 build to work?

**Comment by alyst** [comment]
>  Are we ready to merge or do you foresee more changes to this PR in short-term?

I think we can merge to move forward. I guess, though, we will discover some issues not covered by unit tests.

> Does this need to run on the latest 0.7 build to work?

There were some post-beta2 changes, including `Random.seed!()`. The trace refers to BlackBoxOptim.jl:3, which is `using Random`, so it's quite possible that the error is related to these late changes. I've just built julia-0.7.0-rc2 from `release-0.7` branch and the BBO tests pass. RC2 binaries should be published very soon.

**Pull request merged**
