### PR TITLE
Fixes grabbag

### PR DESCRIPTION
**Pull request by alyst**
A grab bag of fixes all around, but mostly targeting Borg MOEA stability and performance.
There are several serious Borg-related bug fixes.

The 3 new features:
  * restarts-based discounting of frontier elements in `EpsBoxArchive`. It improves Borg crossover operator rates calculation, giving more weight to operators that are currently effective. If the method stalls and restarts frequently due to suboptimal operator rates, the weight of old frontier elements should decrease resulting in more uniform rates of crossover operators. Controlled by :theta: Borg MOEA parameter.
  * `RecoverResults` parameter of `OptController` that controls whether intermediate results are returned upon `InterruptException` (true by default) or `InterruptException` is not suppressed.
  * `MaxStepsWithoutProgress` parameter of `OptController`. Controls if the optimization is terminated when there is no epsilon-progress for given number of iterations (Borg restarts do no reset the counter used).

### CODE REVIEW

**Comment by alyst** [comment]
Travis failed once in `CEC09_UP8` test, but other than that it looks ok.

**Comment by robertfeldt** [comment]
Hmm, haven't had time to check the reasons in detail but when benchmarking there is a problem:

````
Sphere, n = 5, optimizer = de_rand_1_bin, run 1 of 10 (0.06% of total runs)
Starting optimization with optimizer BlackBoxOptim.DiffEvoOpt{BlackBoxOptim.FitPopulation{Float64},BlackBoxOptim.SimpleSelector,BlackBoxOptim.DiffEvoRandBin{3},BlackBoxOptim.RandomBound{BlackBoxOptim.RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps
DE modify state:
ERROR: LoadError: MethodError: `trace_state` has no method matching trace_state(::Base.TTY, ::BlackBoxOptim.DiffEvoRandBin{3})
Closest candidates are:
  trace_state(::IO, ::BlackBoxOptim.GeneticOperator, ::Symbol)
  trace_state(::IO, ::BlackBoxOptim.FAGeneticOperatorsMixture, ::Symbol)
  trace_state(::IO, ::BlackBoxOptim.DiffEvoOpt{P<:BlackBoxOptim.Population,S<:BlackBoxOptim.IndividualsSelector,M<:BlackBoxOptim.GeneticOperator,E<:BlackBoxOptim.EmbeddingOperator}, ::Symbol)
  ...
 in trace_state at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/differential_evolution.jl:33
 in trace_progress at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/opt_controller.jl:231
 in run! at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/opt_controller.jl:273
 in run! at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/opt_controller.jl:407
 in bboptimize at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/bboptimize.jl:69
 in bboptimize at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/bboptimize.jl:68
 in fitness_for_opt at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/examples/benchmarking/compare_optimizers.jl:221
 in compare_optimizers_to_benchmarks at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/examples/benchmarking/compare_optimizers.jl:384
 in main at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/examples/benchmarking/compare_optimizers.jl:125
 in include at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in process_options at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
while loading /Users/feldt/tmp/bbo/BlackBoxOptim.jl/examples/benchmarking/compare_optimizers.jl, in expression starting on line 52
ERROR: LoadError: failed process: Process(`julia --color=yes -L ../../src/BlackBoxOptim.jl compare_optimizers.jl compare --benchmarkfile benchmark_runs_160312.csv --numreps 10`, ProcessExited(1)) [1]
 in run at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in include at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in process_options at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.4.5/lib/julia/sys.dylib
while loading /Users/feldt/tmp/bbo/BlackBoxOptim.jl/examples/benchmarking/runcompare.jl, in expression starting on line 11
````

Any ideas why?

**Comment by alyst** [comment]
My fault: I've added `mode` to the `trace_state()`, but one of the calls was not updated.
It wasn't covered by tests (since tests set `mode` to `:silent`). Now I've fixed it and also added the test that `trace_state()` works for every optimization method.

**Comment by robertfeldt** [comment]
Ok, np. `rake bench` can be a sanity check in addition to `rake test`... :) Anyway, big thanks for your work here. It will be great to support multi-objective opt. Running benchmarking as we speak to avoid regressions.

**Comment by robertfeldt** [comment]
Hmm, I want to investigate this some more. There are many more differences when benchmarking than is usual:

````
Num problems (with p-values < 0.01) = 28
  Num where new implementation is better = 10
  Num where new implementation is worse = 18
...
Num significant at Benjamini-Hochberg 0.05 level: 27
````

It also seems like the difference is quite a lot larger when new implementation is worse, i.e. they differ more than the counts above indicate. Can you see any reason some of the changes might affect many different search methods?

**Comment by robertfeldt** [comment]
Very hard to pinpoint specific change that could lead to a difference when there are so many changed files in one go... We may have to step through the commits in different subsets to see if there is a point where difference gets more noticeable. It is very hard to debug stochastic algorithms like these... ;)

**Comment by alyst** [comment]
Oh, that's bad. Thanks for running the benchmark. The PR might have affected the `TopListArchive`, because the common archive interface was changed (e.g. some type instability is introduced and all scalar methods are slower as the result). Or it could be mutation operators. I can run `rake bench` myself, but if you could attach the log here, maybe it would be possible to identify the suspects faster.

**Comment by robertfeldt** [comment]
The full log is quite large but here are the ones where old is better than new (your latest) and stat significant at 0.01 level:

````
feldt:~/tmp/bbo/BlackBoxOptim.jl/examples/benchmarking$ grep Yes comparison_20160421_002233.csv | grep "<"
"Schwefel2.21",5,"de_rand_1_bin",1.9764836673865302e-7,"<",0.00036075648781119416,2.3594350968764233e-9,0.01,"Yes",true,true,true
"Schwefel2.21",10,"de_rand_1_bin",8.385163183475541e-5,"<",0.010064645478064061,1.6516045678134963e-8,0.01,"Yes",true,true,true
"Schwefel1.2",5,"de_rand_1_bin",8.80291699954373e-9,"<",2.482223214447266,2.3594350968764233e-9,0.01,"Yes",true,true,true
"Schwefel1.2",10,"de_rand_1_bin",9.395264856190092e-7,"<",14.914446117336416,2.3594350968764233e-9,0.01,"Yes",true,true,true
"Rosenbrock",5,"de_rand_1_bin",3.5870845074894144e-5,"<",0.9250856100564713,4.4829266840652046e-8,0.01,"Yes",true,true,true
"Rosenbrock",10,"de_rand_1_bin",0.0009500954181733943,"<",0.7459875358005255,2.3594350968764233e-9,0.01,"Yes",true,true,true
"Rosenbrock",30,"de_rand_1_bin",8.534779103017128,"<",26.443103711744232,2.3594350968764233e-9,0.01,"Yes",true,true,true
"Rosenbrock",50,"de_rand_1_bin",28.922745850983144,"<",46.0639911742755,2.3594350968764233e-9,0.01,"Yes",true,true,true
"Schwefel2.21",5,"de_rand_1_bin_radiuslimited",1.226273527231776e-7,"<",0.0003189911339105539,2.3594350968764233e-9,0.01,"Yes",true,true,true
"Schwefel2.21",10,"de_rand_1_bin_radiuslimited",4.210416811725116e-5,"<",0.014518208880355649,1.6516045678134963e-8,0.01,"Yes",true,true,true
"Schwefel1.2",5,"de_rand_1_bin_radiuslimited",7.96829301541922e-9,"<",3.4796481618758435,2.3594350968764233e-9,0.01,"Yes",true,true,true
"Schwefel1.2",10,"de_rand_1_bin_radiuslimited",8.498355223407003e-9,"<",7.1478899654177965,2.3594350968764233e-9,0.01,"Yes",true,true,true
"Schwefel1.2",30,"de_rand_1_bin_radiuslimited",0.12864132264454536,"<",4330.136692721939,2.3594350968764233e-9,0.01,"Yes",true,true,true
"Schwefel1.2",50,"de_rand_1_bin_radiuslimited",190.5388286240782,"<",28108.455537136713,2.3594350968764233e-9,0.01,"Yes",true,true,true
"Rosenbrock",5,"de_rand_1_bin_radiuslimited",0.0011211594118302984,"<",0.49095976290520493,7.030408758162678e-5,0.01,"Yes",true,true,true
"Rosenbrock",10,"de_rand_1_bin_radiuslimited",0.047676129649556254,"<",0.39383117086821806,7.07830529062927e-8,0.01,"Yes",true,true,true
"Rosenbrock",30,"de_rand_1_bin_radiuslimited",12.092012893569098,"<",24.350548947833182,5.733427285409708e-6,0.01,"Yes",true,true,true
"Rastrigin",100,"de_rand_1_bin_radiuslimited",80.82876031461677,"<",237.82408940437585,2.3594350968764233e-9,0.01,"Yes",true,true,true
````

Seems it is all de_rand_1_bin both radiuslimited and without? It is the same pattern also for older, saved benchmark files; I just verified also for them. So very likely some bug introduced in relation to de_rand_1_bin_X.

**Comment by alyst** [comment]
It was a stupid typo: I've accidentally set the default DE crossover rate to `cr=0.1` instead of `0.7`, when extracting operator parameters to `DEX_DefaultOptions`. That's why convergence got worse for low-dimensional problems and sometimes a little bit better for the high-dim ones.
I've updated the branch. Now `rake bench` doesn't show the significant differences between the PR and the master at P_value=0.01 after BH correction:
```
│ Row │ Problem        │ NumDims │ Method                        │ OldMedian  │ Order │ NewMedian   │ Pvalue      │ Level │ StatSignDiff │ SignificantBH001 │ SignificantBH005 │ SignificantBH010 │
┝━━━━━┿━━━━━━━━━━━━━━━━┿━━━━━━━━━┿━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━┿━━━━━━━┿━━━━━━━━━━━━━┿━━━━━━━━━━━━━┿━━━━━━━┿━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━┿━━━━━━━━━━━━━━━━━━┥
│ 1   │ "Schwefel2.21" │ 10      │ "de_rand_1_bin_radiuslimited" │ 3.04866e-5 │ "<"   │ 0.000500038 │ 0.000205677 │ 0.01  │ "Yes"        │ false            │ true             │ true             │
│ 2   │ "Ackley"       │ 50      │ "probabilistic_descent"       │ 18.7072    │ "<"   │ 18.9173     │ 0.0089307   │ 0.01  │ "Yes"        │ false            │ false            │ false            │
```

**Comment by robertfeldt** [comment]
Nice catch and good we have the benchmarking runs in place... :) Also indicates that adapting the xover rate dynamically might be called for. I get two failures in with rake test now, do you see them also on your side? Seems no BoundsError is raised in these two apply calls:

```
@fact_throws BoundsError BlackBoxOptim.apply(gibbs, 2.0, 0, 1)
@fact_throws BoundsError BlackBoxOptim.apply(gibbs, 2.0, 4, 1)
```

which seems to be because of the @inbounds in the def:

```
@inline apply(m::UniformMutation, v::Number, dim::Int, target_index::Int) =
    @inbounds return (mins(m.ss)[dim] + rand() * deltas(m.ss)[dim])
```

If benchmarking is ok I'll merge and then take away that inbounds. Or did I miss something?

**Comment by alyst** [comment]
Thanks for merging!

I've set `@inbounds` to remove the potential overhead for some optimization methods that would heavily use `UniformMutation`, but forgot about the tests.

It would be nice if `@inbounds` can look into the function calls that get inlined, then it could be put at the call sites only. But I guess `@inbounds`-less version doesn't introduce any serious performance impact ATM.

**Comment by robertfeldt** [comment]
Ok, great.

@alyst since, thanks to you, we now have the BorgMOEA it seems to me it would be quite easy to add the genetic operators to support also non-float individuals. For example I'm thinking of subset individuals of a fixed size, i.e. given an orig set of values V, one individual is a subset of (unique) integers in the range 1:length(V). Mutation op would basically be to sample a random in in the range while xover would select a fixed position along the subset and switch the tails between the two parents. Would the rest of the BorgMOEA code be able to handle this if we add the operators (and maybe a corresponding SearchSpace) or do you think other parts of the code assumes Float vector individuals?

**Comment by alyst** [comment]
@robertfeldt In principle, `BorgMOEA` is parameterized by the population type `P`, so maybe it would even work out-of-the-box with the population types other than matrix-based `FitPopulation`. `TopListArchive`/`EpsBoxArchive`/`Evaluator` assume that the individuals are vectors, but that should be generalizable in a straightforward way as there is no code specific to individuals representation.

**Comment by alyst** [comment]
@robertfeldt BTW, maybe it would make sense to tag and publish the new version and update README.md to reflect the new features.

**Comment by robertfeldt** [comment]
Thanks, @alyst will check about the non-vector individuals.

I just committed an example of multi-objective opt to the README and cleaned some old stuff up. Can you please take a look before I release this? Currently traveling to Luxemburg so might release this weekend. Thanks.

**Comment by robertfeldt** [comment]
Please check in particular this commit: https://github.com/robertfeldt/BlackBoxOptim.jl/commit/627583e6a54fddcd82b7d4b6c48819982132ba89
if you have the time @alyst

**Comment by robertfeldt** [comment]
Oh, btw now we are just waiting: https://github.com/JuliaLang/METADATA.jl/pull/5009

**Pull request merged**
