### PR TITLE
Fix NES

### LINKED ISSUE #26: Invvestigate why xNES and SeparableNES often prematurely converge
Not seeing the expected performance from these two optimizers. Maybe some bug has crept in? Investigate.

### PR DESCRIPTION
**Pull request by alyst**
This should hopefully fix #26.

There were two overlayed bugs related to `assign_weights()`:
  * instead of `u[sortperm(...)]` it should have done `u[invperm(sortperm(...))]` as utility weights are applied not to the ranked candidates, but to the original random samples 
  * `assign_weights()` received candidates already sorted by fitness, so `sortperm()` was useless

Unfortunately, besides generic convergence test, there's no test that would detect such bug. Probably, there should be a test checking the properties of a natural gradient at each step or something like that.

### CODE REVIEW

**Comment by alyst** [comment]
Now looking at [xNES implementations](http://schaul.site44.com/nes.html) and comparing with BlackBoxOptim code...

**Comment by robertfeldt** [comment]
Sounds good, I'll look into this in more detail. If you look at existing code please be aware of the licenses attached; I'd would not want to risk including code that could be argued to be based on non-MIT or non-BSD licensed code. I've tried to implement things from the base research papers to avoid any such future threats to our license.

**Comment by alyst** [comment]
Sure. I was just checking if the other implementations are doing the same thing as written in papers. No code was copied.

**Comment by robertfeldt** [comment]
Great, I just wanted this to be very clear and that we have it documented here on github. Thanks.

**Comment by alyst** [comment]
I've just committed a patch for another serious bug: the indices of candidates were not reset after each iteration that resulted in incorrect assignment of utilities functions. Maybe this time it really fixes the method.

**Comment by alyst** [comment]
Well, it was not the end of the story. There was also a problem with the evaluation and numerical stability of the exponential. Separating `sigma` and `ln(B)` (`tr(ln(B))==0`), like it is usually presented in the literature, should be more stable. Also, it allows using different learning rates for `sigma` and `B`.

To check that the NES behaves as expected, I've implemented `trace_state(optimizer)` that is called by `trace_progress(opt_controller)`. And now it really looks ok.

As a bonus, I've implemented DX-NES (distance-weighted extension of xNES by [N. Fukushima et al.](http://dx.doi.org/10.1109/CEC.2011.5949614)). They show it has the same performance as CMA-ES.

**Comment by robertfeldt** [comment]
Impressed by these fixes and extensions. Thanks for your continued efforts! Running benchmarks today but then plan to merge.

**Comment by robertfeldt** [comment]
Got this when benchmarking dxnes:

````
Schwefel1.2, n = 30, optimizer = dxnes, run 1 of 2
Starting optimization with optimizer DXNESOpt{Float64,RandomBound{RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps
0.50 secs, 13715 evals, 1055 steps, fitness=37663.468529644
1.01 secs, 26910 evals, 2070 steps, fitness=37663.468529644
1.52 secs, 39819 evals, 3063 steps, fitness=37663.468529644
2.02 secs, 52715 evals, 4055 steps, fitness=37663.468529644
2.54 secs, 65624 evals, 5048 steps, fitness=37663.468529644
3.06 secs, 78520 evals, 6040 steps, fitness=37663.468529644
3.57 secs, 91429 evals, 7033 steps, fitness=37663.468529644
ERROR: assertion failed: target[10]=NaN is out of [-100.0, 100.0]
 in error at error.jl:21
 in apply! at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/genetic_operators/embedding/random_bound.jl:27
 in update_parameters! at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/natural_evolution_strategies.jl:164
 in tell! at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/dx_nes.jl:98
 in run! at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/opt_controller.jl:173
 in run! at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/opt_controller.jl:282
 in bboptimize at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/bboptimize.jl:49
 in bboptimize at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/src/bboptimize.jl:48
 in fitness_for_opt at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/examples/benchmarking/compare_optimizers.jl:206
 in multitest_opt at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/examples/benchmarking/compare_optimizers.jl:249
 in update_benchmarks at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/examples/benchmarking/compare_optimizers.jl:56
 in main at /Users/feldt/tmp/bbo/BlackBoxOptim.jl/examples/benchmarking/compare_optimizers.jl:118
 in include at /usr/local/Cellar/julia/0.3.11/lib/julia/sys.dylib
 in include_from_node1 at loading.jl:128
 in process_options at /usr/local/Cellar/julia/0.3.11/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/0.3.11/lib/julia/sys.dylib
while loading /Users/feldt/tmp/bbo/BlackBoxOptim.jl/examples/benchmarking/compare_optimizers.jl, in expression starting on line 52
```

**Comment by alyst** [comment]
I will take a look. You can also set `TraceMode=:verbose` (by default it's `:compact`) to trace the method parameters.

**Comment by alyst** [comment]
I've incorrectly interpreted that evolution path update parameters should be recalculated at every iteration. In fact, it should be done only at start. Should be fixed now.

**Comment by robertfeldt** [comment]
Sounds weird that the evo path params should only be updated at the start but I haven't studied that paper in detail so will take your word for it. Benchmarking looks very nice and the dxnes is actually the best method so far (I have only run 2 reps per method yet though). Merging now and will then run more benchmarking before updating README and toplist. Thanks again.

**Comment by alyst** [comment]
Thanks for merging!

**Comment by robertfeldt** [comment]
Check the new top list at:

https://github.com/robertfeldt/BlackBoxOptim.jl/blob/master/examples/benchmarking/latest_toplist.csv

dxnes comes out on top on mean rank when doing 10 repetitions of 23 different problem configs. Good work and interesting!

**Comment by alyst** [comment]
Oh, that's cool. Thanks for benchmarking!
Though I think the parameter update rule needs to be revisited, because once I've for sigma going to infinity for one of my problems.

**Pull request merged**
